import Navbar from 'components/Navbar';
import Providers from 'components/Providers';
import readContent from 'services/content';
import { homeSchema } from 'utils/content/homeContentValidation';

import { Lato } from 'next/font/google';

import '../globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const locale = 'en';

const lato = Lato({
  subsets: ['latin-ext'],
  weight: ['400', '700', '900'],
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const content = await readContent('content/home.json', locale, homeSchema);

  return (
    <html lang={locale} data-theme="tomTheme" className={lato.className}>
      <body>
        <Providers content={content} locale={locale}>
          <Navbar />
          Holis!
        </Providers>
      </body>
    </html>
  );
}
