import Footer from 'components/Footer';
import Navbar from 'components/Navbar';
import Providers from 'components/Providers';
import readContent from 'services/content';
import { homeSchema } from 'utils/content/homeContentValidation';

import { Lato } from 'next/font/google';

import '../../globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const lato = Lato({
  subsets: ['latin-ext'],
  weight: ['400', '700', '900'],
});

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: {
    locale: 'en' | 'es';
  };
}) {
  const content = await readContent('content/home.json', locale, homeSchema);

  return (
    <html lang={locale} data-theme="tomTheme" className={lato.className}>
      <body className="flex flex-col min-h-screen">
        <Providers content={content} locale={locale}>
          {/* @ts-expect-error */}
          <Navbar locale={locale} />
          <div className="flex flex-col grow pt-[64px]">{children}</div>
          {/* @ts-expect-error */}
          <Footer locale={locale} />
        </Providers>
      </body>
    </html>
  );
}
